server:
  port: 8082
spring:
  application:
    name: Menu
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Menu
      username: mongouser
      password: changemeinProd!
      authentication-database: admin